apiVersion: v2
name: project_name
description: A Helm chart for Kubernetes
type: application
version: 3.4.2-SNAPSHOT
dependencies:
  - name: prometheus
    version: 12.0.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: metrics.enabled
  - name: grafana
    version: 6.1.8
    repository: https://grafana.github.io/helm-charts
    condition: metrics.enabled
