name: 2 Create Release Candidate or Final Build

on:
  workflow_dispatch:
    branches:
      - master
    inputs:             
      release_branch:
        description: 'Build version(e.g. \n3.0.0-RC1 or 3.0.0-HF1-RC1 or 3.0.0 for a final build)'
        required: true
        default: '3.0.0-RC1'
      build_type:
        type: choice
        description: 'Build action'
        required: true
        options:
        - Build Release Candidate
        - Build Final Stable Release
        default: 'Build Release Candidate'
jobs:
  release-candidate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install Git
      run: sudo apt-get update && sudo apt-get install -y git
    - name: Install Maven
      uses: actions/setup-java@v1
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: GIT comitter configuration
      run: |
        git config --global user.email "bogdan.buta@atos.net"
        git config --global user.name "Bogdan Buta"
    - name: GIT check for branch and setup environment
      run: |
        BRANCH="VERSION-${{ github.event.inputs.release_branch }}"
        git ls-remote --exit-code --heads origin $BRANCH >/dev/null 2>&1
        EXIT_CODE=$?
        if [[ $EXIT_CODE == '0' ]]; then
            echo "Git branch '$BRANCH' exists in the remote repository"
            git fetch
            git checkout $BRANCH
            git fetch --tags
            tag=$(git describe --tags --abbrev=0)
            if [[ $tag =~ ([0-9]+)\.([0-9]+)\.([0-9]+)-RC([0-9]+)-SNAPSHOT ]]; then
                echo "Release candidate can be released based on version $tag"
            else
                echo "Currently working on version $tag. Make sure you run the correct workflow."
                exit 1
            fi
            git checkout master            
        elif [[ $EXIT_CODE == '2' ]]; then
            echo "Git branch '$BRANCH' does not exist in the remote repository"
            exit 1
        fi        
        echo "BRANCH=$BRANCH" >> $GITHUB_ENV
        
        final=""     
        if [[ "${{ github.event.inputs.build_type }}" == "Build Final Stable Release" ]]; then
            echo "Script was called with option: Build Final Stable Release"
            final="final"
        else
            echo "Script was called with option: Build Release Candidate"
        fi
        
        echo "FINAL=$final" >> $GITHUB_ENV
    - name: Pre-build version preparation
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY        
        echo "Will work on branch : $BRANCH" 
        echo "Will run final build: $FINAL"
             
        #source ci/build_release_candidate.sh
        #build_version=$(get_next_release_version $BRANCH)        
        
        #BRANCH="VERSION-${{ github.event.inputs.release_branch }}"
        #if [[ ${{ github.event.inputs.final_release }} == "true" ]]; then
        #    preBuildPreparation $BRANCH final
        #else
        #    preBuildPreparation $BRANCH
        #fi
        #
        #ON_BRANCH=$(git rev-parse --abbrev-ref HEAD)
        #echo "Running on branch $ON_BRANCH"
    - name: Run build script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ON_BRANCH=$(git rev-parse --abbrev-ref HEAD)
        echo "Running on branch $ON_BRANCH"
        echo "Build script will run here"
    - name: Post-build version preparation
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ON_BRANCH=$(git rev-parse --abbrev-ref HEAD)
        echo "Running on branch $ON_BRANCH"
        #return to master
        #git checkout master
        #source ci/build_release_candidate.sh
        #BRANCH="VERSION-${{ github.event.inputs.release_branch }}"
        #postBuildActions $BRANCH
    

        
        
