name: 1 Create Release Branch

on:
  workflow_dispatch:
    branches:
      - master
    inputs:
      release_type:
        type: choice
        description: 'Release type'
        required: true
        options:
        - major
        - minor
        - patch
        default: 'patch'
jobs:
  release-candidate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install Git
      run: sudo apt-get update && sudo apt-get install -y git
    - name: Install Maven
      uses: actions/setup-java@v1
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: GIT comitter configuration
      run: |
        git config --global user.email "glaucio.porcidesczekailo@atos.net"
        git config --global user.name "Glaucio Czekailo"
    - name: Run ci script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        echo "Will create a ${{ github.event.inputs.release_type }} release branch"
        bash ci/create_release_branch.sh ${{ github.event.inputs.release_type }}
