name: Prepare Minor Release Candidate

on:
  workflow_dispatch:

jobs:
  create-release-candidate-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create release candidate branch
      run: |
        echo "Preparation started for a minor releases"
