name: Simple Workflow

on:
  workflow_dispatch:
    branches:
      - VERSION-2.0.1

jobs:
  release-candidate:
    runs-on: ubuntu-latest
    steps:    
    - name: Echo something
      run: echo "Something"
